name: MakeRFC
on: [push]
jobs:
  Build-RFC:
    runs-on: ubuntu-latest
    container:
      image: upnic/makerfc
      volumes:
        - /home/runner/work/specs-seguranca/specs-seguranca:/data
    steps:
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: ls-data
        run: ls /data
      - name: ls-root
        run: ls /
#        run: cd /data && /usr/local/bin/make.sh open-banking-brasil-financial-api-1_ID3-ptbr.md
