name: MakeRFC
on: [push]
jobs:
  Build-RFC:
    runs-on: ubuntu-latest
    container:
      image: upnic/makerfc
      volumes:
        - /home/runner/work/specs-seguranca/specs-seguranca:/data
    steps:
      - name: open-banking-brasil-financial-api-1_ID3-ptbr.md
        run: cd /data && /usr/local/bin/make.sh open-banking-brasil-financial-api-1_ID3-ptbr.md
